# Generated by Django 3.2 on 2023-04-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学业要求id')),
                ('credit', models.FloatField(default=0, null=True, verbose_name='要求学分')),
                ('compulsory', models.FloatField(default=0, null=True, verbose_name='必修课成绩')),
                ('elective', models.FloatField(default=0, null=True, verbose_name='选修课成绩')),
                ('physical', models.FloatField(default=0, null=True, verbose_name='体测成绩')),
                ('cet4', models.FloatField(default=0, null=True, verbose_name='四级成绩')),
                ('mandarin', models.FloatField(default=0, null=True, verbose_name='普通话成绩')),
            ],
            options={
                'verbose_name': '学业要求',
                'verbose_name_plural': '学业要求',
                'db_table': 'GraduationRequirement',
            },
        ),
        migrations.AddField(
            model_name='shenhe',
            name='extra_points',
            field=models.IntegerField(default=0, null=True, verbose_name='加分'),
        ),
        migrations.AlterField(
            model_name='early_warning',
            name='cet4',
            field=models.FloatField(default=0, null=True, verbose_name='四级成绩'),
        ),
        migrations.AlterField(
            model_name='early_warning',
            name='compulsory',
            field=models.FloatField(default=0, null=True, verbose_name='必修课成绩'),
        ),
        migrations.AlterField(
            model_name='early_warning',
            name='elective',
            field=models.FloatField(default=0, null=True, verbose_name='选修课成绩'),
        ),
        migrations.AlterField(
            model_name='early_warning',
            name='mandarin',
            field=models.FloatField(default=0, null=True, verbose_name='普通话成绩'),
        ),
        migrations.AlterField(
            model_name='early_warning',
            name='minimum',
            field=models.FloatField(default=0, null=True, verbose_name='实修学分'),
        ),
        migrations.AlterField(
            model_name='early_warning',
            name='physical',
            field=models.FloatField(default=0, null=True, verbose_name='体测成绩'),
        ),
        migrations.AlterField(
            model_name='shenhe',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='审核材料id'),
        ),
        migrations.AlterField(
            model_name='shenhe',
            name='leibie',
            field=models.CharField(choices=[('zy', '专业技术能力'), ('cx', '创新创业能力'), ('gl', '管理实践能力'), ('zh', '综合发展能力')], default='zy', max_length=200, verbose_name='材料类别'),
        ),
        migrations.AddConstraint(
            model_name='shenhe',
            constraint=models.CheckConstraint(check=models.Q(('extra_points__gte', 0), ('extra_points__lte', 100)), name='extra_points'),
        ),
        migrations.AddConstraint(
            model_name='graduationrequirement',
            constraint=models.CheckConstraint(check=models.Q(('credit__gte', 0), ('credit__lte', 170)), name='grad_req_credit'),
        ),
        migrations.AddConstraint(
            model_name='graduationrequirement',
            constraint=models.CheckConstraint(check=models.Q(('compulsory__gte', 0), ('compulsory__lte', 100)), name='grad_req_compulsory'),
        ),
        migrations.AddConstraint(
            model_name='graduationrequirement',
            constraint=models.CheckConstraint(check=models.Q(('elective__gte', 0), ('elective__lte', 100)), name='grad_req_elective'),
        ),
        migrations.AddConstraint(
            model_name='graduationrequirement',
            constraint=models.CheckConstraint(check=models.Q(('physical__gte', 0), ('physical__lte', 100)), name='grad_req_physical'),
        ),
        migrations.AddConstraint(
            model_name='graduationrequirement',
            constraint=models.CheckConstraint(check=models.Q(('cet4__gte', 0), ('cet4__lte', 750)), name='grad_req_cet4'),
        ),
        migrations.AddConstraint(
            model_name='graduationrequirement',
            constraint=models.CheckConstraint(check=models.Q(('mandarin__gte', 0), ('mandarin__lte', 100)), name='grad_req_mandarin'),
        ),
        migrations.AddField(
            model_name='early_warning',
            name='grad_req_id',
            field=models.ForeignKey(blank=True, db_column='stu_gradReq_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.graduationrequirement', verbose_name='学业要求id'),
        ),
    ]
